---
title: "Running times"
output: 
  html_document:
    number_sections: true
    toc: true
date: "2024-03-24"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE, results = "hold")
```


This file collect runtimes from applying the BIDA method on simulated data from three discrete networks.

```{r}
library(dplyr)
library(ggplot2)
library(foreach)
library(here)

ncores <- 4
here::i_am("./inst/simulations/output_runtimes.Rmd")
```

```{r, cache = TRUE}

networks <- c("child", "alarm", "win95pts")
simpar_from_filenames <- function(files, colindx = 2:4, names =  c("network", "N", "r")) {
 tmp <- stringr::str_split(files, ".+/|_|.rds", simplify = T)[, colindx] 
 colnames(tmp) <- names
 tmp
}


dfs <- matrix(list(), nrow = 4, ncol = length(networks))
colnames(dfs) <- networks

cl <- parallel::makeCluster(ncores, type="SOCK", outfile = "")
doSNOW::registerDoSNOW(cl)
on.exit(parallel::stopCluster(cl))
verbose <- T 

for (network in networks) {
  cat(network)
  
  name  <- "partitionMCMC"
  files <- list.files(here::here("..", name), network, full.names = T)
  attributes(readRDS(files[1])) 
  imp   <- vapply(files, 
                  function(f) as.double(attributes(readRDS(f))$toc["partitionMCMC"], units = "secs"), numeric(1))
  dfs[[1, network]] <- data.frame(simpar_from_filenames(files), 
                            method = "bida",
                            task = "slearn",
                            value = imp)
  
  
  name  <- "adjsets"
  files <- list.files(here::here("..", name), network, full.names = T)
  lapply(readRDS(files[1]), attributes)
  imp   <- foreach (f = files) %dopar% {
    if (verbose) cat("\n", name, ":", f)
    vapply(readRDS(f), 
           function(x) as.double(attributes(x)$toc, units = "secs"), numeric(1))
  }
  dfs[[2, network]] <- data.frame(simpar_from_filenames(files), 
                                  method = "bida",
                                task = name, 
                                do.call(rbind, imp))
  
  name  <- "MCMCPC_toc"
  tasks <- c("fit", "pdo", "smpl", "tau")
  files <- list.files(here("../simres"), sprintf("%s.+%s", network, name), full.names = T)
  readRDS(files[1])
  imp <- lapply(files, 
                function(f) 
                   vapply(readRDS(f), 
                   function(x) as.double(x[tasks], units = "secs"), numeric(length(tasks))))
  
  dfs[[3, network]] <- data.frame(simpar_from_filenames(rep(files, each = length(tasks))),
                                  method = "bida",
                                  task = rep(tasks, length(imp)),
                                  do.call(rbind, imp))
  
  name  <- "PC05_toc"
  tasks <- c("slearn", "fit", "pdo", "tau")
  files <- list.files(here("../simres"), sprintf("%s.+%s", network, name), full.names = T)
  readRDS(files[1])
  imp <- lapply(files, 
                function(f) 
                   vapply(readRDS(f), 
                   function(x) as.double(x[tasks], units = "secs"), numeric(length(tasks))))
  dfs[[4, network]] <- data.frame(simpar_from_filenames(rep(files, each = length(tasks))),
                                  method = "ida",
                                  task = rep(tasks, length(imp)),
                                  do.call(rbind, imp))
  
   
  # name  <- "smpl"
  # files <- list.files(here::here("..", name), network, full.names = T)
  # lapply(readRDS(files[1]), attributes)
  # imp <- foreach (f = files) %dopar% {
  #   if (verbose) cat("\n", name, ":", f)
  #   vapply(readRDS(f), 
  #          function(x) as.double(attributes(x)$toc, units = "secs"), numeric(2))
  # }
  # 
  # dfs[[3, network]] <- data.frame(simpar_from_filenames(rep(files, each = 2)), 
  #                                 task = rep(c("fit", "smpl"), length(imp)),
  #                                 do.call(rbind, imp))
  # 
}

```


## Distribution of running times
```{r}
# partitionMCMC
dplyr::bind_rows(dfs[1, ]) %>% 
  prettify_df() %>% 
  ggplot(aes(value)) +
  facet_grid(N~network, scales = "free") +
  geom_histogram(position = "identity", alpha = .5, ) +
  xlab("runtime, seconds") +
  ggtitle("PartitionMCMC")

dplyr::bind_rows(dfs[2, ]) %>% 
  tidyr::pivot_longer(-c(1:4), names_to = "adjset") %>% 
  prettify_df() %>% 
  ggplot(aes(N, value, fill = task)) +
  facet_grid(network ~adjset, scales = "free") +
  geom_boxplot() +
  ylab("runtime, seconds") + xlab("sample size, N") +
  ggtitle("Identify adjustment set")

dplyr::bind_rows(dfs[3, ]) %>% 
  tidyr::pivot_longer(any_of(c("o", "pa", "o_min", "pa_min")), names_to = "adjset") %>% 
  prettify_df() %>% 
  ggplot(aes(N, value, fill = task)) +
  facet_grid(task + network ~adjset, scales = "free") +
  geom_boxplot() +
  ylab("runtime, seconds") + xlab("sample size, N") +
  ggtitle("Fit backdoor params and sample")

dplyr::bind_rows(dfs[4, ]) %>% 
  tidyr::pivot_longer(any_of(c("o", "pa", "o_min", "pa_min")), names_to = "adjset") %>% 
  prettify_df() %>% 
  ggplot(aes(N, value, fill = task)) +
  facet_grid(task + network ~adjset, scales = "free") +
  geom_boxplot() +
  ylab("runtime, seconds") + xlab("sample size, N") +
  ggtitle("IDA")


```

# Compute averages
```{r}
tmp <-lapply(dfs, function(df) aggregate(df[, -c(1:5)], df[, c("method", "network", "N", "task")], "mean"))
dim(tmp) <- dim(dfs)

dfs_slearn <- list()
dfs_slearn$bida <- bind_rows(tmp[1, ]) %>% 
          select(-task) %>% 
          rename(slearn = x)
dfs_slearn$ida <- bind_rows(tmp[4, ]) %>% 
  filter(task == "slearn") %>% 
  select(-task, -o) %>% 
  rename(slearn = pa)

df_agg <- bind_rows(dfs_slearn) %>% 
          left_join(bind_rows(tmp[-c(1), ]), by = c("method", "network", "N"), multiple = "all") %>% 
          filter(task != "slearn") %>% 
        prettify_df()

saveRDS(df_agg, here::here("./inst/simulations/runtimes.rds"))

#ggsave("./../final/graphs/runtimes_decomp.png", plot,  width = 8, height = 4)
```

# Plot table 
```{r}
# aggregate all task but "pdo" and compare ida with bida
tab <- df_agg %>% 
  filter(task != "pdo") %>% 
  tidyr::pivot_longer(c("pa", "o", "o_min", "pa_min"), names_to = "adjset") %>% 
  group_by(method, network, N, slearn, adjset) %>% 
  summarize(value = sum(value), .groups = "drop") %>% 
  mutate(value = paste(round(value, 1))) %>% 
  arrange(method, adjset, network, N) %>% 
  tidyr::pivot_wider(names_from = "adjset")

to_cols <- c("method", "adjset")
sep_by <- "network"

```


```{r}
labs <- c(adjsets = "Identify unique adjustment sets",
          fit = "Upd. hyperparams",
          smpl = "Sample from posterior and compute means")

df_agg %>% 
  filter(method == "bida") %>% 
  mutate(task = ifelse(task == "tau", "smpl", task)) %>% 
  tidyr::pivot_longer(c("o", "o_min", "pa_min", "pa"), names_to = "adjset") %>% 
  prettify_df() %>% 
  mutate(new_task = factor(task, names(labs), labs))  %>% 
  ggplot(aes(adjset, value, fill = task)) +
  facet_grid(network ~N, scales = "free_y") +
  geom_col(position = position_stack(reverse = TRUE)) +
  plot_adjust_theme(axis.text.x = element_text(), ylab = "", xlab = "adjustment set") +
  scale_fill_manual(values = unname(col_scheme[["adjset"]][-1]), name = "")

ggsave(here("inst/simulations/graphs", "runtimes_decomp.png"), plot,  width = 8, height = 4)
```



