---
title: 'Test: posterior_sample.bida_pair'
author: "Vera Kvisgaard"
date: "2024-08-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```


```{r}
here::here("./inst/rmd/posterior_sample.bida_pair_bdeu.Rmd")

library(bida)
library(ggplot2)

# load network
bn <- readRDS(here::here("./data/child.rds"))
n <- length(bn)
nlev <- sapply(bnlearn::rbn(bn, 1), nlevels)
dag <- bnlearn::amat(bn)

seq_n  <- seq_len(n)
dindx <- diag(length(bn)) == 1

JSD <- function(p, k = dim(p)) {
  if (length(k) == 2) {
    dim(p) <- c(k, 1) 
  }
  perm <- c(2, 1, 3)
  bida:::avg_jsd_array(aperm(p, perm), k[perm], 10)
}

# compute ground truth
truth <- list()
truth$pdo <- interv_probs_from_bn(bn, "exact")
truth$jsd <- matrix(vapply(truth$pdo, JSD, numeric(1)), n, n)


samplesizes <- round(10**seq(2, 4, length.out = 5))
rmse <- list(pdo = list(), jsd = list())
N <- 100

dimnames <- list(N = samplesizes, 
                 x = seq_len(n),
                 y = seq_len(n),
                 var = c("posterior_mean","jsd"))
res <- array(dim = lengths(dimnames), dimnames = dimnames)

for (i in seq_along(samplesizes)) {
  N <- samplesizes[i]
  set.seed(N)
  data <- sample_data_from_bn(bn, N)
  for (x in seq_n) {
    #cat(sprintf("\nSample size: %s, x: %s", N, x))
    sets <- matrix(seq_n[dag[, x] == 1], nrow = 1) 
    for (y in seq_n[-x]) {
      
      pair <- bida:::bida_pair("cat", data, y, x, sets, 1, list(ess = 1, nlev = nlev))
      mean    <- posterior_mean(pair)
      res[i, x, y, 1] <- mean( (mean-truth$pdo[[x, y]])**2 )
      #smpl   <- posterior_sample(pair, 1000)
      #stopifnot(abs(mean-rowMeans(smpl, dims = 2)) < 10e-2)
      jsd  <- posterior_mean(pair, contrasts = list(jsd = JSD))
      res[i, x, y, 2] <- (jsd-truth$jsd[x, y])**2   
    }
  }
}

df <- tidyr::pivot_wider(reshape2::melt(res), names_from = "var")
head(df)
```

```{r}
library(ggplot2)
ggplot(df, aes(N, sqrt(posterior_mean), colour = interaction(y))) +
  facet_wrap(x~., scales = "free") +
  geom_line() +
  theme(legend.position = "none") +
  scale_x_log10()

ggplot(df, aes(N, sqrt(jsd), colour = interaction(x, y))) +
  facet_wrap(x~., scales = "free") +
  geom_line() +
  theme(legend.position = "none") +
  scale_x_log10()
```



